### ISSUE TITLE
报错了

### ISSUE THREAD

**Issue by donghang54321** [Cangol/Cangol-actionbar#3]
java.lang.RuntimeException: Unable to start activity ComponentInfo{com.rentian.newoa/com.rentian.newoa.modules.task.view.Main3Activity}: android.view.InflateException: Binary XML file line #15: Binary XML file line #15: Error inflating class mobi.cangol.mobile.actionbar.view.ActionBarView
                                                                       at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2984)
                                                                       at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:3045)
                                                                       at android.app.ActivityThread.-wrap14(ActivityThread.java)
                                                                       at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1642)
                                                                       at android.os.Handler.dispatchMessage(Handler.java:102)
                                                                       at android.os.Looper.loop(Looper.java:154)
                                                                       at android.app.ActivityThread.main(ActivityThread.java:6776)
                                                                       at java.lang.reflect.Method.invoke(Native Method)
                                                                       at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:1520)
                                                                       at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1410)
                                                                    Caused by: android.view.InflateException: Binary XML file line #15: Binary XML file line #15: Error inflating class mobi.cangol.mobile.actionbar.view.ActionBarView
                                                                    Caused by: android.view.InflateException: Binary XML file line #15: Error inflating class mobi.cangol.mobile.actionbar.view.ActionBarView
                                                                    Caused by: java.lang.reflect.InvocationTargetException
                                                                       at java.lang.reflect.Constructor.newInstance0(Native Method)
                                                                       at java.lang.reflect.Constructor.newInstance(Constructor.java:430)
                                                                       at android.view.LayoutInflater.createView(LayoutInflater.java:652)
                                                                       at android.view.LayoutInflater.createViewFromTag(LayoutInflater.java:794)
                                                                       at android.view.LayoutInflater.createViewFromTag(LayoutInflater.java:734)
                                                                       at android.view.LayoutInflater.rInflate(LayoutInflater.java:865)
                                                                       at android.view.LayoutInflater.rInflateChildren(LayoutInflater.java:828)
                                                                       at android.view.LayoutInflater.inflate(LayoutInflater.java:525)
                                                                       at android.view.LayoutInflater.inflate(LayoutInflater.java:427)
                                                                       at android.view.LayoutInflater.inflate(LayoutInflater.java:378)
                                                                       at mobi.cangol.mobile.actionbar.ActionBarActivityDelegate.onCreate(ActionBarActivityDelegate.java:40)

**Comment by Cangol** [comment]
请问你用的是哪个版本？你可以跑一下我的demo，看是否正常
还有Main3Activity这个你要使用“ActionBarTheme.Dark”或“ActionBarTheme.Light” 这些theme，或者全局使用这些theme
